### ISSUE TITLE
Support ES2015 in unexpected-markdown

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-markdown#2]
Converation on Gitter:

@papandreou How hard do you think it would be to support babel es2015 in unexpected-markdown's test runner?

papandreou 09:33
@sunesimonsen Easy, esprima supports it, so the manipulation of the code fragments should already be up for it. A bit harder if running the test suite still has to work on older node.js versions, that'll require us to hook into babel and make sure that we hand over the source map we have generated correctly. @gustavnikolaj, do you know if Babel supports picking up existing source maps?
We might need to teach the code manipulation code that non-block fat arrow functions have an implicit return. It detects returns at the top level because they have to be rewritten.

@sunesimonsen @gustavnikolaj Good news, babel had another use case for supporting existing source maps, so it's already there, according to https://phabricator.babeljs.io/T827
I think our road map looks something like this:
1) Make sure that the source files we generate have a serialized inline source map at the end. I've avoided that until now because there's a bit of overhead involved, but I think we can manage.
2) See to it that the way lib/UnexpectedError.js (the main file) hooks into require (via require.extensions['.md'] = function (module, fileName) {...}) is compatible with babel so it will transpile the resulting code, if necessary.
3) Fix detection of fat arrow returns so those can be patched up as well

**Comment by papandreou** [comment]
I got it to work now on the feature/integrateWithBabelAndSourceMapSupport branch.

I added a branch in Unexpected that shows how to use it: https://github.com/unexpectedjs/unexpected/tree/feature/babelAndSourceMapSupport

(not that we want to integrate it into Unexpected)

Try checking out the branch, `npm install`, then `npm link unexpected-markdown` with `feature/integrateWithBabelAndSourceMapSupport` checked out, then run `mocha documentation/index.md`

That will show a failing ES6 code snippet that was read from index.md, converted to a mocha test suite, then transpiled via babel, and then the stack trace is correctly mapped back to the original index.md source location :)

**Comment by sunesimonsen** [comment]
That is completely awesome, looking forward to try it.

**Comment by sunesimonsen** [comment]
I get the following error when trying it
```
/Users/sunesimonsen/Code/unexpected/node_modules/babel-core/lib/transformation/file/index.js:556
      throw err;
      ^

Error: unknown: Invalid mapping: {"generated":{"line":4,"column":38,"lastColumn":null},"source":null,"original":{"line":null,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/sunesimonsen/Code/unexpected/node_modules/source-map/lib/source-map-generator.js:271:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/sunesimonsen/Code/unexpected/node_modules/source-map/lib/source-map-generator.js:101:14)
    at /Users/sunesimonsen/Code/unexpected/node_modules/babel-core/lib/transformation/file/index.js:450:29
    at Array.forEach (native)
```

**Comment by sunesimonsen** [comment]
it is this transformation that fails:

```js
        var babelResult = babelCore.transform(code, extend({}, babelOptions, {
            sourceMaps: true,
            inputSourceMap: JSON.parse(map)
        }));
```

**Comment by sunesimonsen** [comment]
Babel Core version 6.7.2

**Comment by papandreou** [comment]
Ah, you know what, I also ran into that while trying to get it to work, and I ended up editing `source-map-generator.js` locally to not throw that error.

**Comment by papandreou** [comment]
I spent some time poking around and trying to avoid it. Seems like the `SourceMapGenerator` employed by babel doesn't like a few of the mappings in the existing source map we hand to it. I'll need to dig further to know where the bug is, could be that I'm using escodegen wrong or that I fail to treat the location information correctly when I manipulate the AST.

In the mean time you can go to `/Users/sunesimonsen/Code/unexpected/node_modules/source-map/lib/source-map-generator.js:271:15` and remove the `throw` or replace it with a `console.log` so those wrong invalid mappings are skipped. That makes it work for me -- seems like there are sufficient *valid* mappings for the resulting source map to do its job.

**Comment by sunesimonsen** [comment]
Thanks for looking at it. I can do that hack and made the actual html generation work in the meantime.

**Comment by papandreou** [comment]
https://phabricator.babeljs.io/T7151

**Comment by papandreou** [comment]
The branch now works with the `File.prototype.mergeSourceMap` replacement suggested by jscheid on that issue.

**Comment by sunesimonsen** [comment]
Super awesome - thanks
