### ISSUE TITLE
Setup linting on Travis and add badges.

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-markdown#7]
We should use onelint.

**Comment by gustavnikolaj** [comment]
Linting is changed to onelint and added on travis. Only badges to go from here.

https://github.com/unexpectedjs/unexpected-markdown/commit/f5db99f2cb24d41d426e6f763c8d226132ee5a28

https://github.com/unexpectedjs/unexpected-markdown/commit/2f4f86b79e9d4132273ff8899e620553bc16d12c

**Comment by sunesimonsen** [comment]
Ouch that was a lot of mistakes it caught 😀
